apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qo7t9g3yx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qo7t9g3yx-python 
  name: qo7t9g3yx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qo7t9g3yx-python 
